
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            4140
     no. of nonzeroes in lower triangle of a =           39601
     no. of nonzeroes in the factor l        =          305433
     ratio of nonzeroes in factor (min/max)  =          0.8504
     number of super nodes                   =             242
     maximum order of a front matrix         =             185
     maximum size of a front matrix          =           17205
     maximum size of a front trapezoid       =           10184
     no. of floating point ops for factor    =      2.1101D+07
     no. of floating point ops for solve     =      1.0241D+06
     ratio of flops for factor (min/max)     =          0.7509
     ratio of allocated memory (max/min)     =          1.2017
     Number of positive pivots               =            4061
     Number of negative pivots               =              79
     Number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.002268
     time (cpu & wall) for ordering          =        0.000000        0.022030
     time (cpu & wall) for other matrix prep =        0.000000        0.011632
     time (cpu & wall) for value input       =        0.000000        0.000954
     time (cpu & wall) for matrix distrib.   =        0.000000        0.034303
     time (cpu & wall) for numeric factor    =        0.015625        0.015731
     computational rate (gflops) for factor  =        1.350491        1.341382

     no input or output performed

  Solver Memory allocated on core    0       =        1.609 MB
  Solver Memory allocated on core    1       =        1.422 MB
  Solver Memory allocated on core    2       =        1.573 MB
  Solver Memory allocated on core    3       =        1.339 MB
  Total Solver Memory allocated by all cores =        5.943 MB

